<?php
/**
 * Hook Manager Class
 *
 * Manages WordPress hooks registration and execution for WPTSALL.
 *
 * v0.6.0 Changes:
 * - Updated to use many-to-many relation-model associations
 * - Auto-generates hooks from associated models (not single template)
 * - Different hook logic for virtual sites vs WP sites
 *
 * v0.7.0 Changes:
 * - wp_wptsall_hooks table is deprecated
 * - All hooks are now auto-generated by generate_auto_hooks()
 * - Database-related methods (get_hooks_from_database, save_hook, etc.) marked as @deprecated
 * - Kept for backward compatibility, will be removed in future versions
 *
 * @package WPTSALL\Hooks
 * @since 0.5.0
 * @updated 0.7.0 Deprecated database hooks in favor of auto-generation
 */

namespace WPTSALL\Hooks;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Hook_Manager class
 *
 * Handles dynamic hook registration based on templates and site relations.
 */
class Hook_Manager {

	/**
	 * Registered hooks tracking
	 *
	 * @var array
	 */
	private static $registered = array();

	/**
	 * Cache for hooks table existence check
	 *
	 * @var bool|null
	 */
	private static $hooks_table_exists = null;

	/**
	 * Per-request cache for custom-table existence checks in hot hook paths.
	 *
	 * @var array
	 */
	private static $table_exists_cache = array();

	/**
	 * Tracks which relations have already been regenerated in this request.
	 *
	 * Prevents duplicate anonymous closure registration since WordPress
	 * cannot remove previously registered anonymous callbacks.
	 *
	 * @since 1.2.0
	 * @var array
	 */
	private static $regenerated_relations = array();

	/**
	 * Check if the hooks table exists
	 *
	 * The hooks table was deprecated in v0.7.0 and removed in v0.9.0.
	 * This method is used to prevent database errors when calling
	 * deprecated methods that operate on the hooks table.
	 *
	 * @since 0.9.0
	 * @return bool True if table exists, false otherwise.
	 */
	private static function hooks_table_exists() {
		if ( null !== self::$hooks_table_exists ) {
			return self::$hooks_table_exists;
		}

		global $wpdb;
		$table = wptsall_table( 'hooks' );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$result = $wpdb->get_var(
			$wpdb->prepare( 'SHOW TABLES LIKE %s', $table )
		);

		self::$hooks_table_exists = ( $result === $table );

		return self::$hooks_table_exists;
	}

	/**
	 * Initialize the hook manager
	 *
	 * @return void
	 */
	public static function init() {
		add_action( 'plugins_loaded', array( __CLASS__, 'register_dynamic_hooks' ) );

		// Listen for relation updates to regenerate hooks.
		add_action( 'wptsall_relation_updated', array( __CLASS__, 'regenerate_hooks_for_relation' ) );
		add_action( 'wptsall_relation_models_updated', array( __CLASS__, 'regenerate_hooks_for_relation' ) );
	}

	/**
	 * Regenerate hooks for a specific site relation
	 *
	 * Called when a relation is updated or its associated models change.
	 * Clears the tracking state for the relation so new hooks will be
	 * registered on the next call to register_dynamic_hooks().
	 *
	 * Note: WordPress doesn't support removing anonymous function callbacks,
	 * so previously attached closures remain until the request ends.
	 *
	 * @since 0.9.0
	 *
	 * @param int $relation_id Site relation ID.
	 * @return void
	 */
	public static function regenerate_hooks_for_relation( $relation_id ) {
		$relation_id = intval( $relation_id );

		if ( ! $relation_id ) {
			return;
		}

		// Prevent duplicate hook registration for same relation in same request.
		if ( isset( self::$regenerated_relations[ $relation_id ] ) ) {
			return;
		}
		self::$regenerated_relations[ $relation_id ] = true;

		wptsall_log_info(
			'hooks-manager',
			'Regenerating hooks for relation',
			array( 'relation_id' => $relation_id )
		);

		// Clear registered hooks for this relation from the tracking array.
		$cleared_count = 0;
		foreach ( self::$registered as $key => $value ) {
			// Key format: hook_name|site_id|model_id|template|subtype
			$parts = explode( '|', $key );
			if ( isset( $parts[1] ) && intval( $parts[1] ) === $relation_id ) {
				unset( self::$registered[ $key ] );
				++$cleared_count;
			}
		}

		wptsall_log_info(
			'hooks-manager',
			'Hook tracking cleared for relation, will re-register on next request',
			array(
				'relation_id'   => $relation_id,
				'cleared_count' => $cleared_count,
			)
		);
	}

	/**
	 * Generate deduplication key for a hook configuration
	 *
	 * @since 0.9.0
	 *
	 * @param array $hook Hook configuration array.
	 * @return string Unique key for deduplication.
	 */
	public static function get_dedup_key( $hook ) {
		return $hook['hook_name']
			. '|' . ( $hook['site_id'] ?? '' )
			. '|' . ( $hook['model_id'] ?? '' )
			. '|' . ( $hook['template'] ?? '' )
			. '|' . ( $hook['expected']['subtype'] ?? '' );
	}

	/**
	 * Register dynamic hooks from database and auto-generated sources
	 *
	 * @return void
	 */
	public static function register_dynamic_hooks() {
		$hooks = self::collect_hooks();

		wptsall_log_debug(
			'hooks-manager',
			'Starting dynamic hook registration',
			array( 'total_hooks' => count( $hooks ) )
		);

		$registered_count = 0;

		foreach ( $hooks as $hook ) {
			if ( 'enabled' !== $hook['status'] ) {
				continue;
			}

			// v0.6.0: Include model_id in deduplication key.
			// v0.9.0: Use get_dedup_key() helper method.
			$key = self::get_dedup_key( $hook );

			if ( isset( self::$registered[ $key ] ) ) {
				continue;
			}

			self::$registered[ $key ] = true;
			$priority                 = intval( $hook['priority'] ?? 10 );
			$accepted_args            = intval( $hook['accepted_args'] ?? 5 );

			if ( class_exists( __NAMESPACE__ . '\\Virtual_Site_Query_Switch' )
				&& Virtual_Site_Query_Switch::is_frontend_delivery_hook( $hook['hook_name'] ) ) {
				continue;
			}

			add_action(
				$hook['hook_name'],
				function ( $arg1 = null, $arg2 = null, $arg3 = null, $arg4 = null, $arg5 = null ) use ( $hook ) {
					self::run_hook_action( $hook, array( $arg1, $arg2, $arg3, $arg4, $arg5 ) );
				},
				$priority,
				$accepted_args
			);

			$registered_count++;
		}

		wptsall_log_info(
			'hooks-manager',
			'Dynamic hooks registered',
			array( 'registered_count' => $registered_count )
		);
	}

	/**
	 * Collect hooks from auto-generated sources
	 *
	 * @return array
	 */
	public static function collect_hooks() {
		return self::generate_auto_hooks();
	}

	/**
	 * Generate automatic hooks based on site relations and associated models
	 *
	 * v0.6.0: Updated to use many-to-many relation-model associations.
	 * Each site relation can have multiple models, hooks are generated for all.
	 *
	 * v0.9.0: Added optional $relation_id parameter to generate hooks for a specific relation only.
	 *
	 * @param int|null $relation_id Optional. If provided, only generate hooks for this relation.
	 * @return array
	 */
	public static function generate_auto_hooks( $relation_id = null ) {
		$auto_hooks = array();

		// Get relations - either a single one or all.
		if ( null !== $relation_id ) {
			$relation = \WPTSALL\Sites\Services\Site_Relation_Service::get_relation( $relation_id );
			$relations = $relation ? array( $relation ) : array();
		} else {
			$relations = \WPTSALL\Sites\Services\Site_Relation_Service::get_all_relations();
		}

		if ( empty( $relations ) ) {
			return $auto_hooks;
		}

		foreach ( $relations as $relation ) {
			$relation_id = (int) $relation['id'];

			// v0.6.0: Get all models associated with this relation.
			$models = \WPTSALL\Sites\Services\Relation_Model_Service::get_models_by_relation( $relation_id );

			if ( empty( $models ) ) {
				// Fall back to legacy template field if no models associated.
				$template_slug = $relation['template'] ?? '';
				if ( $template_slug ) {
					$tpl = \WPTSALL\Models\Services\Plugin_Mapping_Service::get_by_slug( $template_slug );
					if ( $tpl ) {
						$models = array( $tpl );
					}
				}
			}

			if ( empty( $models ) ) {
				continue;
			}

			// Determine if this is for a virtual site or WP site.
			$is_virtual_target = ( $relation['target_site_type'] ?? '' ) === 'virtual';
			$is_wp_source      = ( $relation['source_site_type'] ?? 'wp' ) === 'wp';

			// Generate hooks for each associated model.
			foreach ( $models as $model ) {
				$model_hooks = self::generate_model_hooks( $relation, $model, $is_virtual_target, $is_wp_source );
				$auto_hooks  = array_merge( $auto_hooks, $model_hooks );
			}
		}

		return $auto_hooks;
	}

	/**
	 * Generate hooks for a single model within a site relation
	 *
	 * @since 0.6.0
	 *
	 * @param array $relation         Site relation data.
	 * @param array $model            Model data.
	 * @param bool  $is_virtual_target Whether target is a virtual site.
	 * @param bool  $is_wp_source     Whether source is a WP site.
	 * @return array Generated hooks.
	 */
	private static function generate_model_hooks( $relation, $model, $is_virtual_target, $is_wp_source ) {
		$hooks       = array();
		$relation_id = (int) $relation['id'];
		$model_id    = (int) ( $model['id'] ?? 0 );
		$model_slug  = $model['plugin_slug'] ?? '';

		// Parse post_types and taxonomies (handle both JSON string and array).
		$post_types = self::parse_model_objects( $model['post_types'] ?? array() );
		$taxonomies = self::parse_model_objects( $model['taxonomies'] ?? array() );

		if ( empty( $post_types ) && empty( $taxonomies ) ) {
			return $hooks;
		}

		// Post type hooks - only for WP source sites (trigger on content changes).
		if ( ! empty( $post_types ) && $is_wp_source ) {
			foreach ( $post_types as $pt ) {
				$pt_name = is_array( $pt ) ? ( $pt['name'] ?? $pt['subtype'] ?? '' ) : $pt;
				if ( ! $pt_name ) {
					continue;
				}
				if ( ! self::post_type_is_listenable( $pt_name ) ) {
					continue;
				}

				// Specific post type save hook.
				$hooks[] = array(
					'hook_name' => 'save_post_' . $pt_name,
					'site_id'   => $relation_id,
					'model_id'  => $model_id,
					'template'  => $model_slug,
					'status'    => 'enabled',
					'priority'  => 10,
					'expected'  => array(
						'object_type' => 'post_type',
						'subtype'     => $pt_name,
					),
				);

				// Delete/trash hooks (use generic hooks with subtype filter).
				foreach ( array( 'delete_post', 'trash_post' ) as $hook_name ) {
					$hooks[] = array(
						'hook_name' => $hook_name,
						'site_id'   => $relation_id,
						'model_id'  => $model_id,
						'template'  => $model_slug,
						'status'    => 'enabled',
						'priority'  => 10,
						'expected'  => array(
							'object_type' => 'post_type',
							'subtype'     => $pt_name,
						),
					);
				}
			}

			// Generic save_post fallback.
			$hooks[] = array(
				'hook_name' => 'save_post',
				'site_id'   => $relation_id,
				'model_id'  => $model_id,
				'template'  => $model_slug,
				'status'    => 'enabled',
				'priority'  => 10,
				'expected'  => array(
					'object_type' => 'post_type',
					'subtype'     => '',
				),
			);

			// Gutenberg / REST / CLI primary insert path (4 args; ID is first).
			$hooks[] = array(
				'hook_name'     => 'wp_after_insert_post',
				'site_id'       => $relation_id,
				'model_id'      => $model_id,
				'template'      => $model_slug,
				'status'        => 'enabled',
				'priority'      => 10,
				'accepted_args' => 4,
				'expected'      => array(
					'object_type' => 'post_type',
					'subtype'     => '',
				),
			);

			// Status transitions (dirty-mark; target status sync is Content_Change_Dispatcher).
			$hooks[] = array(
				'hook_name'     => 'transition_post_status',
				'site_id'       => $relation_id,
				'model_id'      => $model_id,
				'template'      => $model_slug,
				'status'        => 'enabled',
				'priority'      => 10,
				'accepted_args' => 3,
				'expected'      => array(
					'object_type' => 'post_type',
					'subtype'     => '',
				),
			);
		}

		// Taxonomy hooks - only for WP source sites.
		if ( ! empty( $taxonomies ) && $is_wp_source ) {
			foreach ( $taxonomies as $tax ) {
				$tax_name = is_array( $tax ) ? ( $tax['name'] ?? $tax['subtype'] ?? '' ) : $tax;
				if ( ! $tax_name ) {
					continue;
				}

				foreach ( array( 'created_term', 'edited_term', 'delete_term' ) as $tax_hook ) {
					$hooks[] = array(
						'hook_name' => $tax_hook,
						'site_id'   => $relation_id,
						'model_id'  => $model_id,
						'template'  => $model_slug,
						'status'    => 'enabled',
						'priority'  => 10,
						'expected'  => array(
							'object_type' => 'taxonomy',
							'subtype'     => $tax_name,
						),
					);
				}
			}

			// Generic taxonomy hooks fallback.
			foreach ( array( 'created_term', 'edited_term', 'delete_term' ) as $tax_hook ) {
				$hooks[] = array(
					'hook_name' => $tax_hook,
					'site_id'   => $relation_id,
					'model_id'  => $model_id,
					'template'  => $model_slug,
					'status'    => 'enabled',
					'priority'  => 10,
					'accepted_args' => 3,
					'expected'  => array(
						'object_type' => 'taxonomy',
						'subtype'     => '',
					),
				);
			}
		}

		// Post-meta / term-relationship listen events (dirty-mark only).
		// Frontend delivery hooks (template_include / pre_get_posts / …)
		// are owned by Virtual_Site_Router and must not be listen events.
		if ( $is_wp_source && ( ! empty( $post_types ) || ! empty( $taxonomies ) ) ) {
			foreach ( array( 'added_post_meta', 'updated_post_meta', 'deleted_post_meta' ) as $meta_hook ) {
				$hooks[] = array(
					'hook_name'     => $meta_hook,
					'site_id'       => $relation_id,
					'model_id'      => $model_id,
					'template'      => $model_slug,
					'status'        => 'enabled',
					'priority'      => 10,
					'accepted_args' => 4,
					'expected'      => array(
						'object_type' => 'post_type',
						'subtype'     => '',
					),
				);
			}
			$hooks[] = array(
				'hook_name'     => 'set_object_terms',
				'site_id'       => $relation_id,
				'model_id'      => $model_id,
				'template'      => $model_slug,
				'status'        => 'enabled',
				'priority'      => 10,
				'accepted_args' => 6,
				'expected'      => array(
					'object_type' => 'post_type',
					'subtype'     => '',
				),
			);
			$hooks[] = array(
				'hook_name'     => 'edit_attachment',
				'site_id'       => $relation_id,
				'model_id'      => $model_id,
				'template'      => $model_slug,
				'status'        => 'enabled',
				'priority'      => 10,
				'accepted_args' => 1,
				'expected'      => array(
					'object_type' => 'post_type',
					'subtype'     => 'attachment',
				),
			);
		}

		return $hooks;
	}

	/**
	 * Parse model objects (post_types or taxonomies)
	 *
	 * Handles both JSON string and array formats.
	 *
	 * @since 0.6.0
	 *
	 * @param mixed $data Data to parse.
	 * @return array Parsed array.
	 */
	private static function parse_model_objects( $data ) {
		if ( empty( $data ) ) {
			return array();
		}

		if ( is_string( $data ) ) {
			$decoded = json_decode( $data, true );
			return is_array( $decoded ) ? $decoded : array();
		}

		return is_array( $data ) ? $data : array();
	}

	/**
	 * Get site relation by ID
	 *
	 * @param int|string $id Site relation ID.
	 * @return array|null
	 */
	public static function get_site_rel( $id ) {
		return \WPTSALL\Sites\Services\Site_Relation_Service::get_relation( $id );
	}

	/**
	 * Get model by ID
	 *
	 * @since 0.6.0
	 *
	 * @param int $model_id Model ID.
	 * @return array|null Model data or null if not found.
	 */
	public static function get_model_by_id( $model_id ) {
		global $wpdb;
		$table = wptsall_table( 'models' );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.PreparedSQLPlaceholders.UnsupportedIdentifierPlaceholder
		$model = $wpdb->get_row(
			$wpdb->prepare(
				'SELECT * FROM %i WHERE id = %d',
				$table,
				$model_id
			),
			ARRAY_A
		);

		if ( ! $model ) {
			return null;
		}

		// Parse JSON fields to match expected format.
		$model['post_types'] = self::parse_model_objects( $model['post_types'] ?? '' );
		$model['taxonomies'] = self::parse_model_objects( $model['taxonomies'] ?? '' );

		return $model;
	}

	/**
	 * Run hook action - queue tasks for later processing
	 *
	 * v0.6.0: Updated to use model_id for direct model lookup.
	 * v0.8.0: Disabled direct sync execution. Tasks are now queued and
	 *         processed by Monitoring_Task_Service or Task_Orchestrator.
	 *
	 * @param array $hook Hook configuration.
	 * @param array $args Hook arguments.
	 * @return void
	 */
	public static function run_hook_action( $hook, $args = array() ) {
		if ( class_exists( __NAMESPACE__ . '\\Content_Change_Dispatcher' )
			&& Content_Change_Dispatcher::is_internal_write() ) {
			return;
		}
		$hook_name = (string) ( $hook['hook_name'] ?? '' );
		if ( self::is_frontend_delivery_hook( $hook_name ) ) {
			return;
		}
		if ( self::is_post_meta_hook_name( $hook_name ) ) {
			$meta_key = isset( $args[2] ) ? (string) $args[2] : '';
			if ( self::should_ignore_listen_meta_key( $meta_key ) ) {
				return;
			}
		}
		$object_id = self::extract_listen_object_id( $hook_name, $args );
		if ( $object_id <= 0 ) {
			return;
		}

		$source_site_id = get_current_blog_id();
		global $wpdb;
		$now = current_time( 'mysql' );
		$updated = 0;
		$table = '';
		$id_column = '';

		if ( self::is_taxonomy_hook_name( $hook_name ) ) {
			$table     = wptsall_table( 'term_mappings' );
			$id_column = 'source_term_id';
		} else {
			$table     = wptsall_table( 'post_mappings' );
			$id_column = 'source_post_id';
		}

		// P1-TEST-01 perf (2026-09-02): every dynamic hook fired by a single
		// wp_insert_post() used to issue its own SHOW TABLES probe (1200+
		// queries per insert in the unit suite). Cache the existence check
		// per table for the lifetime of the request.
		if ( ! array_key_exists( $table, self::$table_exists_cache ) ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
			self::$table_exists_cache[ $table ] = ( $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $table ) ) === $table );
		}
		if ( self::$table_exists_cache[ $table ] ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
			$updated = (int) $wpdb->query(
				$wpdb->prepare(
					'UPDATE %i SET needs_resync = 1, updated_at = %s WHERE %i = %d AND source_site_id = %d AND needs_resync = 0',
					$table,
					$now,
					$id_column,
					$object_id,
					$source_site_id
				)
			);
		}

		if ( $updated > 0 ) {
			wptsall_log_info(
				'hooks-manager',
				'Marked mappings for resync',
				array(
					'hook_name'      => $hook_name,
					'object_id'      => $object_id,
					'mapping_table'  => $table,
					'source_site_id' => $source_site_id,
					'rows_marked'    => $updated,
				)
			);
		}
	}

	/**
	 * Extract source object ID from hook callback args.
	 *
	 * Supports both associative payloads and native WordPress positional args.
	 *
	 * @param string $hook_name Hook name.
	 * @param array  $args      Hook args.
	 * @return int
	 */
	/**
	 * Public listen extractor for unit tests and Hook_Manager.
	 *
	 * @param string $hook_name Hook name.
	 * @param array  $args      Hook args.
	 * @return int
	 */
	public static function extract_listen_object_id( $hook_name, $args ) {
		return self::extract_object_id_from_hook_args( $hook_name, $args );
	}

	/**
	 * Whether this hook is a frontend delivery hook (must not dirty-mark).
	 *
	 * @param string $hook_name Hook name.
	 * @return bool
	 */
	public static function is_frontend_delivery_hook( $hook_name ) {
		if ( class_exists( __NAMESPACE__ . '\\Virtual_Site_Query_Switch' ) ) {
			return Virtual_Site_Query_Switch::is_frontend_delivery_hook( $hook_name );
		}
		return in_array(
			(string) $hook_name,
			array( 'template_include', 'template_redirect', 'pre_get_posts', 'parse_request' ),
			true
		);
	}

	/**
	 * Whether this hook is a post-meta mutation event.
	 *
	 * @param string $hook_name Hook name.
	 * @return bool
	 */
	public static function is_post_meta_hook_name( $hook_name ) {
		return in_array(
			(string) $hook_name,
			array( 'added_post_meta', 'updated_post_meta', 'deleted_post_meta' ),
			true
		);
	}

	/**
	 * Meta keys that must not trigger dirty-mark (locks, internal markers).
	 *
	 * @param string $meta_key Meta key.
	 * @return bool
	 */
	public static function should_ignore_listen_meta_key( $meta_key ) {
		$meta_key = (string) $meta_key;
		if ( '' === $meta_key ) {
			return false;
		}
		if ( 0 === strpos( $meta_key, '_wptsall_' ) ) {
			return true;
		}
		return in_array( $meta_key, array( '_edit_lock', '_edit_last' ), true );
	}

	/**
	 * Classify a listen hook as post or term mapping target.
	 *
	 * @param string $hook_name Hook name.
	 * @return string 'term'|'post'
	 */
	public static function classify_listen_target( $hook_name ) {
		return self::is_taxonomy_hook_name( $hook_name ) ? 'term' : 'post';
	}

	private static function extract_object_id_from_hook_args( $hook_name, $args ) {
		if ( isset( $args['object_id'] ) ) {
			return (int) $args['object_id'];
		}
		if ( isset( $args['post_id'] ) ) {
			return (int) $args['post_id'];
		}
		if ( isset( $args['term_id'] ) ) {
			return (int) $args['term_id'];
		}

		$hook_name = (string) $hook_name;

		if ( self::is_post_meta_hook_name( $hook_name ) ) {
			return (int) ( $args[1] ?? 0 );
		}

		if ( 'transition_post_status' === $hook_name ) {
			$post = $args[2] ?? null;
			if ( is_object( $post ) && isset( $post->ID ) ) {
				return (int) $post->ID;
			}
			if ( is_array( $post ) && isset( $post['ID'] ) ) {
				return (int) $post['ID'];
			}
			return (int) ( $args[0] ?? 0 );
		}

		$first_arg = $args[0] ?? null;
		if ( is_numeric( $first_arg ) ) {
			return (int) $first_arg;
		}
		if ( is_object( $first_arg ) ) {
			if ( isset( $first_arg->ID ) ) {
				return (int) $first_arg->ID;
			}
			if ( isset( $first_arg->term_id ) ) {
				return (int) $first_arg->term_id;
			}
			return 0;
		}
		if ( is_array( $first_arg ) ) {
			if ( isset( $first_arg['ID'] ) ) {
				return (int) $first_arg['ID'];
			}
			if ( isset( $first_arg['term_id'] ) ) {
				return (int) $first_arg['term_id'];
			}
		}

		return 0;
	}

	/**
	 * Check whether a hook belongs to taxonomy events.
	 *
	 * @param string $hook_name Hook name.
	 * @return bool
	 */
	private static function is_taxonomy_hook_name( $hook_name ) {
		return in_array( $hook_name, array( 'created_term', 'edited_term', 'delete_term' ), true );
	}

	/**
	 * Delete all hooks for a site relation
	 *
	 * @deprecated 0.7.0 Hooks are now auto-generated, this method operates on removed table.
	 * @since 0.9.0 Returns 0 if hooks table doesn't exist.
	 *
	 * @param int $site_id Site relation ID.
	 * @return int Number of deleted hooks.
	 */
	public static function delete_hooks_by_site( $site_id ) {
		// Check if hooks table exists (removed in v0.9.0).
		if ( ! self::hooks_table_exists() ) {
			return 0;
		}

		global $wpdb;

		$table = wptsall_table( 'hooks' );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$result = $wpdb->delete(
			$table,
			array( 'site_id' => intval( $site_id ) )
		);

		$deleted_count = $result ? $result : 0;

		wptsall_log_info(
			'hooks-manager',
			'Hooks deleted by site',
			array(
				'site_id'       => $site_id,
				'deleted_count' => $deleted_count,
			)
		);

		return $deleted_count;
	}

	/**
	 * Whether a post type should generate dirty-mark listen hooks.
	 *
	 * Orders / coupons / ACF internals stay off the generic listen list.
	 * Custom-table rows are not given frontend delivery hooks.
	 *
	 * @since 2.1.0
	 * @param string $post_type Post type.
	 * @return bool
	 */
	public static function post_type_is_listenable( $post_type ) {
		$post_type = sanitize_key( (string) $post_type );
		if ( '' === $post_type ) {
			return false;
		}
		$skip = array(
			'shop_order',
			'shop_order_refund',
			'shop_coupon',
			'shop_subscription',
			'acf-field',
			'acf-field-group',
			'acf-post-type',
			'acf-taxonomy',
			'acf-ui-options-page',
			'scheduled_action',
			'revision',
			'nav_menu_item',
			'custom_css',
			'customize_changeset',
		);
		if ( in_array( $post_type, $skip, true ) ) {
			return false;
		}
		if ( class_exists( '\\WPTSALL\\Models\\Services\\Plugin_Scanner' )
			&& method_exists( '\\WPTSALL\\Models\\Services\\Plugin_Scanner', 'is_excluded_post_type' )
			&& \WPTSALL\Models\Services\Plugin_Scanner::is_excluded_post_type( $post_type ) ) {
			return false;
		}
		return true;
	}

	/**
	 * Get hook recommendations for a plugin
	 *
	 * @param string $plugin_slug Plugin slug.
	 * @return array
	 */
	public static function get_hook_recommendations( $plugin_slug ) {
		$plugin_slug = sanitize_key( $plugin_slug );

		$recommendations = array(
			'woocommerce'              => array(
				'frontend' => array(),
				'save'     => array(
					'save_post_product',
					'created_term',
					'edited_term',
					'delete_term',
				),
				'strings'  => array(
					'gettext',
				),
				'notes'    => __( 'Listen only on save_post_product / term / meta. Frontend delivery is query-switch or the native subsite — display hooks are not registered.', 'wpmmcc-ats' ),
			),
			'bbpress'                  => array(
				'frontend' => array(),
				'save'     => array(
					'bbp_new_forum',
					'bbp_edit_forum',
					'bbp_new_topic',
					'bbp_edit_topic',
					'bbp_new_reply',
					'bbp_edit_reply',
				),
				'notes'    => __( 'Save hooks can enqueue translation tasks for forum/topic/reply; template_include can be used for cache refresh or debugging.', 'wpmmcc-ats' ),
			),
			'easy-digital-downloads'   => array(
				'frontend' => array(),
				'save'     => array(
					'save_post_download',
					'edd_download_updated',
					'created_term',
					'edited_term',
				),
				'notes'    => __( 'Save hooks for downloads and categories/tags can enqueue tasks; frontend template_include can be used for cache refresh.', 'wpmmcc-ats' ),
			),
			'buddypress'               => array(
				'frontend' => array(),
				'save'     => array(
					'bp_activity_posted_update',
					'bp_activity_after_save',
				),
				'notes'    => __( 'BuddyPress has a complex content structure that requires per-module customization; only basic hook recommendations are provided here.', 'wpmmcc-ats' ),
			),
		);

		if ( isset( $recommendations[ $plugin_slug ] ) ) {
			return $recommendations[ $plugin_slug ];
		}

		return array(
			'notes' => __( 'No hook recommendations defined for this plugin yet.', 'wpmmcc-ats' ),
		);
	}

	/**
	 * Get auto-hooks summary for a site relation
	 *
	 * Returns a summary of hooks that would be auto-generated for a relation.
	 *
	 * @since 0.6.0
	 *
	 * @param int $relation_id Site relation ID.
	 * @return array Summary with counts and hook details.
	 */
	public static function get_relation_hooks_summary( $relation_id ) {
		$relation = \WPTSALL\Sites\Services\Site_Relation_Service::get_relation( $relation_id );
		if ( ! $relation ) {
			return array(
				'error'   => 'Relation not found',
				'total'   => 0,
				'models'  => array(),
			);
		}

		$models = \WPTSALL\Sites\Services\Relation_Model_Service::get_models_by_relation( $relation_id );
		$is_virtual_target = ( $relation['target_site_type'] ?? '' ) === 'virtual';
		$is_wp_source      = ( $relation['source_site_type'] ?? 'wp' ) === 'wp';

		$summary = array(
			'relation_id'       => $relation_id,
			'target_type'       => $is_virtual_target ? 'virtual' : 'wp',
			'source_type'       => $is_wp_source ? 'wp' : 'other',
			'models_count'      => count( $models ),
			'total_hooks'       => 0,
			'post_type_hooks'   => 0,
			'taxonomy_hooks'    => 0,
			'frontend_hooks'    => 0,
			'models'            => array(),
		);

		foreach ( $models as $model ) {
			$model_hooks = self::generate_model_hooks( $relation, $model, $is_virtual_target, $is_wp_source );
			$model_summary = array(
				'model_id'     => $model['id'] ?? 0,
				'plugin_name'  => $model['plugin_name'] ?? '',
				'plugin_slug'  => $model['plugin_slug'] ?? '',
				'hooks_count'  => count( $model_hooks ),
				'post_types'   => array(),
				'taxonomies'   => array(),
			);

			// Parse model objects for summary.
			$post_types = self::parse_model_objects( $model['post_types'] ?? array() );
			$taxonomies = self::parse_model_objects( $model['taxonomies'] ?? array() );

			foreach ( $post_types as $pt ) {
				$model_summary['post_types'][] = is_array( $pt ) ? ( $pt['name'] ?? '' ) : $pt;
			}

			foreach ( $taxonomies as $tax ) {
				$model_summary['taxonomies'][] = is_array( $tax ) ? ( $tax['name'] ?? '' ) : $tax;
			}

			// Count hook types.
			foreach ( $model_hooks as $hook ) {
				$hook_name = $hook['hook_name'] ?? '';
				if ( str_starts_with( $hook_name, 'save_post' ) || in_array( $hook_name, array( 'delete_post', 'trash_post', 'edit_attachment', 'set_object_terms' ), true ) || self::is_post_meta_hook_name( $hook_name ) ) {
					$summary['post_type_hooks']++;
				} elseif ( in_array( $hook_name, array( 'created_term', 'edited_term', 'delete_term' ), true ) ) {
					$summary['taxonomy_hooks']++;
				} elseif ( self::is_frontend_delivery_hook( $hook_name ) ) {
					$summary['frontend_hooks']++;
				}
			}

			$summary['total_hooks'] += count( $model_hooks );
			$summary['models'][]     = $model_summary;
		}

		return $summary;
	}

	/**
	 * Clear registered hooks cache
	 *
	 * Useful when hooks need to be re-registered after model changes.
	 *
	 * @since 0.6.0
	 *
	 * @return void
	 */
	public static function clear_registered_cache() {
		self::$registered = array();

		wptsall_log_info(
			'hooks-manager',
			'Registered hooks cache cleared'
		);
	}

	/**
	 * Get hooks for a specific model
	 *
	 * @since 0.6.0
	 *
	 * @param int $model_id Model ID.
	 * @return array Hooks data.
	 */
	public static function get_hooks_for_model( $model_id ) {
		$model = self::get_model_by_id( $model_id );
		if ( ! $model ) {
			return array();
		}

		// Get all relations that include this model.
		$relations = \WPTSALL\Sites\Services\Relation_Model_Service::get_relations_by_model( $model_id );

		$all_hooks = array();
		foreach ( $relations as $relation ) {
			$is_virtual_target = ( $relation['target_site_type'] ?? '' ) === 'virtual';
			$is_wp_source      = ( $relation['source_site_type'] ?? 'wp' ) === 'wp';

			$hooks = self::generate_model_hooks( $relation, $model, $is_virtual_target, $is_wp_source );
			$all_hooks = array_merge( $all_hooks, $hooks );
		}

		return $all_hooks;
	}

	/**
	 * Get plugin-specific hooks for a model
	 *
	 * Returns plugin-specific hooks (like WooCommerce hooks) that should be
	 * registered in addition to standard hooks.
	 *
	 * @since 0.6.0
	 *
	 * @param array $model     Model data.
	 * @param array $relation  Site relation data.
	 * @return array Additional hooks.
	 */
	public static function get_plugin_specific_hooks( $model, $relation ) {
		$model_id     = (int) ( $model['id'] ?? 0 );
		$plugin_slug  = $model['plugin_slug'] ?? '';
		$relation_id  = (int) $relation['id'];
		$additional_hooks = array();

		// 1. First try to get hooks from database (generated by Model_Scanner_V2 scan)
		if ( $model_id > 0 && class_exists( '\\WPTSALL\\Models\\Services\\Translation_Rule_Service' ) ) {
			$db_hooks = \WPTSALL\Models\Services\Translation_Rule_Service::get_hooks_by_model( $model_id );

			if ( ! empty( $db_hooks ) ) {
				foreach ( $db_hooks as $hook ) {
					$additional_hooks[] = array(
						'hook_name' => $hook['hook_name'],
						'site_id'   => $relation_id,
						'model_id'  => $model_id,
						'template'  => $plugin_slug,
						'status'    => 'enabled',
						'priority'  => $hook['priority'] ?? 10,
						'expected'  => array(
							'object_type' => $hook['data_type'] === 'post' ? 'post_type' : 'taxonomy',
							'subtype'     => $hook['object_name'],
						),
						'source'    => 'database',
						'action'    => $hook['action'] ?? 'update',
					);
				}

				wptsall_log_debug(
					'hooks-manager',
					'Loaded hooks from database',
					array(
						'model_id'    => $model_id,
						'plugin_slug' => $plugin_slug,
						'hook_count'  => count( $additional_hooks ),
					)
				);

				return $additional_hooks;
			}
		}

		// If no hook configuration in database, return empty array
		// Hook configuration should be saved to database during model scan or manual configuration
		return $additional_hooks;
	}
}
