<?php
/**
 * Hooks Functions
 *
 * Global wrapper functions for backward compatibility.
 * Core logic is in Hook_Manager class.
 *
 * @package WPTSALL\Hooks
 * @since 0.4.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use WPTSALL\Hooks\Hook_Manager;

// ISS-HOK-015: BuddyPress directory-page auto-corrections gated behind option (default off).
// Enable via: update_option( 'wptsall_hooks_auto_corrections', true );
// Note: Do NOT register an unprefixed `buddypress` CPT — WordPress.org requires
// CPT identifiers to use a plugin prefix, and it would conflict with real BuddyPress.
if ( get_option( 'wptsall_hooks_auto_corrections', false ) ) {
	add_action( 'init', 'wptsall_ensure_bp_directory_pages', 20 );
}

/**
 * Legacy no-op: previously registered unprefixed CPT `buddypress` (removed in 1.9.0).
 *
 * Kept as a stub so any external callers do not fatally error.
 *
 * @since 1.9.0 No longer registers a CPT.
 * @return void
 */
function wptsall_register_support_post_types() {
	// Intentionally empty — unprefixed CPT registration violated WP.org prefix rules.
}

/**
 * Ensure BuddyPress directory pages are real pages.
 *
 * Gated behind `wptsall_hooks_auto_corrections` option (ISS-HOK-015).
 *
 * @return void
 */
function wptsall_ensure_bp_directory_pages() {
	$bp_pages = get_option( 'bp-pages', array() );
	if ( empty( $bp_pages ) || ! is_array( $bp_pages ) ) {
		return;
	}
	foreach ( $bp_pages as $pid ) {
		$pid = intval( $pid );
		if ( ! $pid ) {
			continue;
		}
		$p = get_post( $pid );
		if ( $p && 'page' !== $p->post_type ) {
			wp_update_post(
				array(
					'ID'          => $pid,
					'post_type'   => 'page',
					'post_status' => 'publish',
				)
			);
			wptsall_log_info(
				'hooks',
				'Auto-corrected BP directory page type',
				array( 'post_id' => $pid, 'old_type' => $p->post_type )
			);
		}
	}
}

/**
 * Get hook recommendations for a plugin
 *
 * @param string $plugin_slug Plugin slug.
 * @return array
 */
function wptsall_hook_recommendations( $plugin_slug ) {
	return Hook_Manager::get_hook_recommendations( $plugin_slug );
}

// Note: wptsall_hook_table_name() removed in v1.1.0 (hooks table removed in v0.9.0)
// Note: wptsall_insert_hook_entry removed in v1.1.0 (deprecated since v0.7.0)
// Note: wptsall_create_hooks_table removed in v0.9.0 (deprecated since v0.7.0)
// Hooks are now auto-generated by Hook_Manager, no database table needed.

/**
 * Register dynamic hooks
 *
 * Wrapper for Hook_Manager::register_dynamic_hooks().
 * Note: Automatic registration on plugins_loaded removed in v1.1.0.
 * Hook-based task queueing was disabled since v0.8.0 (all hooks are no-ops).
 * Call this manually only for diagnostic purposes.
 *
 * @return void
 */
function wptsall_register_dynamic_hooks() {
	Hook_Manager::register_dynamic_hooks();
}

/**
 * Collect all hooks (from DB and auto-generated)
 *
 * @return array
 */
/**
 * Generate automatic hooks based on templates and site relations
 *
 * @return array
 */
function wptsall_generate_auto_hooks() {
	return Hook_Manager::generate_auto_hooks();
}

/**
 * Get site relation by ID
 *
 * @param int|string $id Site relation ID.
 * @return array|null
 */
/**
 * Run hook action - create and process tasks
 *
 * @param array $hook Hook configuration.
 * @param array $args Hook arguments.
 * @return void
 */
