<?php
/**
 * Hooks Module
 *
 * Handles WordPress hooks management and custom hook functionality.
 *
 * @package WPTSALL\Hooks
 * @since 0.4.0
 */

namespace WPTSALL\Hooks;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Hooks Module class
 *
 * Initializes all components of the Hooks module:
 * - Database schemas
 * - Hook Manager class
 * - Hook functions (backward compatible wrappers)
 */
class Module {

	/**
	 * Initialize the module
	 *
	 * @return void
	 */
	public static function init() {
		// Load database schemas
		self::load_schemas();

		// Load classes
		self::load_classes();

		// Load function files (backward compatible wrappers)
		self::load_functions();
	}

	/**
	 * Load database schemas
	 *
	 * Note: schema-hooks.php removed in v0.9.0 (deprecated since v0.7.0)
	 * Hooks are now auto-generated by Hook_Manager, no database table needed.
	 *
	 * @return void
	 */
	private static function load_schemas() {
		// No schemas to load - hooks table deprecated
	}

	/**
	 * Load module classes
	 *
	 * @return void
	 */
	private static function load_classes() {
		$module_path = dirname( __FILE__ );

		// Hook Manager - core hook registration logic
		require_once $module_path . '/class-hook-manager.php';

		// Virtual Site Router - frontend routing and content filtering
		require_once $module_path . '/class-virtual-site-router.php';

		// Query switch: bind virtual-site requests to shadow post/term objects.
		require_once $module_path . '/class-virtual-site-query-switch.php';

		// Virtual Site SEO - hreflang / canonical / robots / sitemap / document_title.
		// Modeled after Polylang PLL_Frontend_Filters_Links and
		// WPML WPML_SEO_HeadLangs. Hooks are registered from
		// Virtual_Site_Router::maybe_register_frontend_hooks().
		require_once $module_path . '/class-virtual-site-seo.php';

		// Link filters (home_url / menus / static pages) + HTML output localizer.
		require_once $module_path . '/class-virtual-site-link-filters.php';
		require_once $module_path . '/class-output-link-localizer.php';

		// Gettext Filter - translation interception
		require_once $module_path . '/class-gettext-filter.php';

		// Config Filter - site config content translation (blogname, menus, widgets)
		require_once $module_path . '/class-config-filter.php';

		// Admin Virtual Site Manager - dynamic virtual site content management
		require_once $module_path . '/class-admin-virtual-site-manager.php';

		// Unified content lifecycle (REST/Gutenberg/CLI + status/trash/delete).
		require_once $module_path . '/class-content-change-dispatcher.php';

		// Initialize hook manager (dynamic hook registration for relations).
		Hook_Manager::init();

		// Initialize frontend hooks
		Virtual_Site_Router::init();
		Gettext_Filter::init();
		Config_Filter::init();
		Content_Change_Dispatcher::init();

		// Admin_Virtual_Site_Manager auto-initializes via constructor (file footer).
	}

	/**
	 * Load function files
	 *
	 * @return void
	 */
	private static function load_functions() {
		$module_path = dirname( __FILE__ );

		// Hooks functions (backward compatible wrappers)
		require_once $module_path . '/hooks.php';
	}
}
