<?php
/**
 * Site Verification for Challenge-Response domain binding.
 *
 * Generates one-time verification nonces and signed responses so the WPTSALL
 * server can prove site ownership before binding a domain.
 *
 * @package WPTSALL\Core
 * @since 1.1.0
 */

namespace WPTSALL\Core;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Site_Verification handles nonce generation, HMAC signing, and RSA encryption
 * for the domain verification challenge-response protocol.
 */
class Site_Verification {

	/**
	 * Default server RSA public key for encrypting site_secret.
	 * This key is generated by the WPTSALL server.
	 * The server holds the private key and can decrypt.
	 *
	 * To rotate the key, define WPTSALL_SERVER_PUBLIC_KEY in wp-config.php.
	 */
	const DEFAULT_SERVER_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoWCa+WUy7VbFkdgcorv4
U4BSUkXt+QHnHzBjyBZrEhscVrMU5Rcd41eVwnxz8GJEvxlasmMtc1JXPctHQmr0
1/LHYtcr497w5EUxeNPdYmkYyW2LccGrXOb5j4MbOU1BlTSNsblZ7Gztj6Jaw6l8
wtdfizGJdt9zB6N67xwczYA+dDX70z38KVDDBB9FpBZKFmbNoYnideiGDTxEpI8P
EEjcxWYm1az0ikUGTGomtAku4AFfgmrL/3GZMg39hAdGePIEUSXKjtDgfr9n9lXA
nSYEGO4zjH7PJs+eRC339phRKHDj4QrnAYLYIbxSTHJdzsJhDvhiBtDOAIp5JMNG
JQIDAQAB
-----END PUBLIC KEY-----';

	/**
	 * Get the server public key, allowing override via wp-config.php constant.
	 *
	 * @return string PEM-encoded RSA public key.
	 */
	public static function get_server_public_key() {
		return defined( 'WPTSALL_SERVER_PUBLIC_KEY' ) ? WPTSALL_SERVER_PUBLIC_KEY : self::DEFAULT_SERVER_PUBLIC_KEY;
	}

	/**
	 * Verification nonce TTL in seconds.
	 *
	 * @var int
	 */
	const NONCE_TTL = 600; // 10 minutes

	/**
	 * WordPress option key for site secret.
	 *
	 * @var string
	 */
	const SITE_SECRET_OPTION = 'wptsall_site_secret';

	/**
	 * Transient prefix for verification nonces.
	 *
	 * @var string
	 */
	const TRANSIENT_PREFIX = 'wptsall_site_verify_';

	/**
	 * Get or generate the site secret (32 bytes hex).
	 * Generated once per WP installation, stored in wp_options.
	 *
	 * @return string 64-character hex string.
	 */
	public static function get_site_secret() {
		$secret = get_option( self::SITE_SECRET_OPTION );
		if ( empty( $secret ) || strlen( $secret ) !== 64 ) {
			$secret = bin2hex( random_bytes( 32 ) );
			update_option( self::SITE_SECRET_OPTION, $secret, false ); // autoload=false
		}
		return $secret;
	}

	/**
	 * Generate a one-time verification nonce.
	 *
	 * @return array {
	 *     @type string $nonce            UUID4 nonce.
	 *     @type string $verification_url Full REST URL for server to fetch.
	 *     @type int    $expires_at       Unix timestamp.
	 *     @type int    $expires_in       TTL in seconds.
	 * }
	 */
	public static function generate_verification_nonce() {
		// Validate that current site uses a real domain name (not IP/localhost).
		$domain = wptsall_get_current_site_domain();
		if ( ! wptsall_validate_domain_format( $domain ) ) {
			return new \WP_Error(
				'invalid_domain',
				sprintf(
					'Site domain "%s" is not a valid domain name. IP addresses and localhost are not supported for site verification.',
					$domain
				),
				array( 'status' => 400 )
			);
		}

		$nonce      = wp_generate_uuid4();
		$expires_at = time() + self::NONCE_TTL;

		$data = array(
			'nonce'      => $nonce,
			'site_url'   => home_url(),
			'expires_at' => $expires_at,
			'created_at' => time(),
		);

		set_transient( self::TRANSIENT_PREFIX . $nonce, $data, self::NONCE_TTL );

		$verification_url = rest_url( 'wptsall/v2/site/verify' ) . '?nonce=' . $nonce;

		return array(
			'nonce'            => $nonce,
			'verification_url' => $verification_url,
			'expires_at'       => $expires_at,
			'expires_in'       => self::NONCE_TTL,
		);
	}

	/**
	 * Consume a verification nonce and return signed response data.
	 *
	 * @param string $nonce UUID4 nonce from the verification URL.
	 * @return array|\WP_Error Signed response on success, WP_Error on failure.
	 */
	public static function consume_nonce_and_sign( $nonce ) {
		$data = get_transient( self::TRANSIENT_PREFIX . $nonce );
		if ( empty( $data ) ) {
			return new \WP_Error( 'verification_expired', 'Verification nonce expired or not found', array( 'status' => 404 ) );
		}

		// Check expiry.
		if ( time() > $data['expires_at'] ) {
			delete_transient( self::TRANSIENT_PREFIX . $nonce );
			return new \WP_Error( 'verification_expired', 'Verification nonce expired', array( 'status' => 410 ) );
		}

		// Delete transient (one-time use).
		delete_transient( self::TRANSIENT_PREFIX . $nonce );

		$site_url       = $data['site_url'];
		$expires_at     = $data['expires_at'];
		$plugin_version = defined( 'WPTSALL_VERSION' ) ? WPTSALL_VERSION : '1.0.0';

		// Get site secret.
		$site_secret = self::get_site_secret();

		// Build canonical message.
		$canonical = self::build_canonical_message( $site_url, $nonce, $expires_at, $plugin_version );

		// Sign with HMAC-SHA256.
		$signature = hash_hmac( 'sha256', $canonical, hex2bin( $site_secret ) );

		// Encrypt site secret with server public key (RSA-OAEP).
		$encrypted_secret = self::encrypt_site_secret( $site_secret );
		if ( is_wp_error( $encrypted_secret ) ) {
			return $encrypted_secret;
		}

		return array(
			'site_url'         => $site_url,
			'nonce'            => $nonce,
			'expires_at'       => $expires_at,
			'plugin_version'   => $plugin_version,
			'signature'        => $signature,
			'encrypted_secret' => $encrypted_secret,
			'route_secret'     => function_exists( 'wptsall_get_client_route_secret' )
				? wptsall_get_client_route_secret()
				: '',
		);
	}

	/**
	 * Build canonical message for HMAC signing.
	 *
	 * Fields sorted alphabetically, URL-encoded values, joined with &.
	 *
	 * @param string $site_url       Site URL.
	 * @param string $nonce          Verification nonce.
	 * @param int    $expires_at     Expiry timestamp.
	 * @param string $plugin_version Plugin version string.
	 * @return string Canonical message string.
	 */
	public static function build_canonical_message( $site_url, $nonce, $expires_at, $plugin_version ) {
		$fields = array(
			'expires_at'     => (string) $expires_at,
			'nonce'          => $nonce,
			'plugin_version' => $plugin_version,
			'site_url'       => $site_url,
		);
		ksort( $fields );

		$parts = array();
		foreach ( $fields as $key => $value ) {
			$parts[] = rawurlencode( $key ) . '=' . rawurlencode( $value );
		}
		return implode( '&', $parts );
	}

	/**
	 * Encrypt site secret with server RSA public key (OAEP padding).
	 *
	 * @param string $site_secret_hex 64-character hex site secret.
	 * @return string|\WP_Error Base64-encoded ciphertext or WP_Error.
	 */
	public static function encrypt_site_secret( $site_secret_hex ) {
		$public_key = openssl_pkey_get_public( self::get_server_public_key() );
		if ( ! $public_key ) {
			return new \WP_Error( 'encryption_failed', 'Cannot load server public key' );
		}

		$plaintext = hex2bin( $site_secret_hex );
		$encrypted = '';
		$success   = openssl_public_encrypt( $plaintext, $encrypted, $public_key, OPENSSL_PKCS1_OAEP_PADDING );

		if ( ! $success ) {
			return new \WP_Error( 'encryption_failed', 'RSA encryption failed: ' . openssl_error_string() );
		}

		return base64_encode( $encrypted );
	}
}
